version: "3.3"

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: jalvaro
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: my-store
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@pgadmin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - postgres

volumes:
  postgres-data:
