version: 1
env: node
services:
  app:
    build:
      base: node:16
      commands:
        - npm install
        - npm run migrations:run
    run:
      env:
        NODE_ENV: production
      command: npm run start
